swagger: "2.0"
info:
  description: "Aplicativo para envio de emails."
  title: "SendMail API"
  version: "1.0"
paths:
  /notification/sendmail:
    post:
      summary: "Enviar um email"
      description: "Envie um email com assunto e corpo personalizado"
      tags:
        - "Enviar um email"
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - name: "to"
          in: "body"
          required: true
          type: "string"
          description: "Informe o email de envio"
          schema: {}
        - name: "subject"
          in: "body"
          required: true
          type: "string"
          description: "Informe o Título da Mensagem"
          schema: {}
        - name: "text"
          in: "body"
          required: true
          type: "string"
          description: "Informe o Corpo da Mensagem"
          schema: {}
      responses:
        "200":
          description: "E-mail enviado com sucesso"
          schema:
            type: "string"
